//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dubl2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IlyasovEntities : DbContext
    {
        public IlyasovEntities()
            : base("name=IlyasovEntities")
        {
        }
        private static IlyasovEntities _context;
        public static IlyasovEntities GetContext()
        {
            if(_context == null)
                _context = new IlyasovEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Edinisi_izmereniy> Edinisi_izmereniy { get; set; }
        public virtual DbSet<Materiali> Materiali { get; set; }
        public virtual DbSet<Materiali_produksiy> Materiali_produksiy { get; set; }
        public virtual DbSet<Produksii> Produksii { get; set; }
        public virtual DbSet<Tipi_materialov> Tipi_materialov { get; set; }
        public virtual DbSet<Tipi_produksiy> Tipi_produksiy { get; set; }
    }
}
