//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dubl2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiali_produksiy
    {
        public int ID { get; set; }
        public int Produksia { get; set; }
        public int Naimenovanie_materiala { get; set; }
        public decimal Neobhodimoe_kolichetvo_materiala { get; set; }
    
        public virtual Materiali Materiali { get; set; }
        public virtual Produksii Produksii { get; set; }

        public decimal CountPrice
        {
            get
            {
                return Materiali.Sena_edinisi_materiala;
            }
        }
    }
}
