//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dubl2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiali
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materiali()
        {
            this.Materiali_produksiy = new HashSet<Materiali_produksiy>();
        }
    
        public int ID { get; set; }
        public string Naimenovania_materiala { get; set; }
        public int Tip_materiala { get; set; }
        public decimal Sena_edinisi_materiala { get; set; }
        public int Kolichestvo_na_sklade { get; set; }
        public int Minimalnoe_kolichestvo { get; set; }
        public int Kolichestvo_v_upakovke { get; set; }
        public int Edinisa_izmerenia { get; set; }
    
        public virtual Edinisi_izmereniy Edinisi_izmereniy { get; set; }
        public virtual Tipi_materialov Tipi_materialov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materiali_produksiy> Materiali_produksiy { get; set; }
    }
}
