//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dubl2
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Produksii
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produksii()
        {
            this.Materiali_produksiy = new HashSet<Materiali_produksiy>();
        }
    
        public int Artikul { get; set; }
        public int Tip_produksii { get; set; }
        public string Naimenovanie_produksii { get; set; }
        public decimal Minimalnya_stoimost_dlya_partnera { get; set; }
        public double Shirina_rulona { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materiali_produksiy> Materiali_produksiy { get; set; }
        public virtual Tipi_produksiy Tipi_produksiy { get; set; }

        public string TypeP
        {
            get
            {
                return Tipi_produksiy.Tip_produksii;
            }
        }
        public decimal CostProduct
        {
            get
            {
                return Math.Round(Materiali_produksiy.Sum(s => s.Neobhodimoe_kolichetvo_materiala * s.CountPrice), 2);
            }
        }
    }
}
