//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dubl2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipi_materialov
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipi_materialov()
        {
            this.Materiali = new HashSet<Materiali>();
        }
    
        public int ID { get; set; }
        public string Tip_materiala { get; set; }
        public decimal Procent_braka_materiala { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materiali> Materiali { get; set; }
    }
}
