//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dubl2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipi_produksiy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipi_produksiy()
        {
            this.Produksii = new HashSet<Produksii>();
        }
    
        public int ID { get; set; }
        public string Tip_produksii { get; set; }
        public double K_tipa_produksii { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produksii> Produksii { get; set; }
    }
}
